print("Hello World")
print(5 > 3)
print(5 != 5)
print(6**5)
print(type(5))
print(5*5)
print(25//25)
print(5%5)
print(36%2)
print(2.0)
print(type(2.0))
print("1"+"3")
print(int("5"))
print(type(int("5")))
example = "Коловрат"
print(example[::3])
print(example[::-1])
print(example[:3])
print(example[3:])
